### Get logged in users info

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJvYiIsImlhdCI6MTcxMzQzMzA4Nn0.wVuJ3WFzOMijkJkW6kUzcl_PnD723_VIdgajNWXjbxk

### Sign Up

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "lordjohnson",
    "password": "1234",
    "email": "kdev82707@gmail.com"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "britney",
    "password": "1234"
}

###

POST http://localhost:3000/users/forgotpassword
Content-Type: application/json

{
    "username": "Test"
}

###

POST http://localhost:3000/users/changepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpYXQiOjE3MTQwNDYwNzZ9.QCRUlMdbvr0mcaFKF11JyL0DM1P04FvDV5fTAhdYgPA
Content-Type: application/json

{
    "password": "newpassword"
}

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMjM0IiwiaWF0IjoxNzE1Mjc3Mjc1fQ.eGDFnk05JEJ5TVsMWtd3LpkKNHJ6zvismkGGxV750gk

###

POST http://localhost:3000/users/addfriend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMjM0IiwiaWF0IjoxNzE1Mjc3Mjc1fQ.eGDFnk05JEJ5TVsMWtd3LpkKNHJ6zvismkGGxV750gk
Content-Type: application/json

{
    "friendUsername": "add friend test"
}

###

GET http://localhost:3000/users/exists/johnbob

###

GET http://localhost:3000/users/isconnected/johnbob


### 

POST http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5ib2IiLCJpYXQiOjE3MTU2NzM1OTV9.GA6yk1Z1FCTZgl2e41me1pD33RIDdw2l1TUEW8OYji4
Content-Type: application/json

{
    "content": "crazy wow"
}

###

GET http://localhost:3000/posts?page1&limit=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyaXRuZXkiLCJpYXQiOjE3MTU2NzkwODF9.g0VQQzaeaq-so4JH0c37oJNRkbXllMkJwi1rBDMduaY


###

POST http://localhost:3000/posts/66434be39a43c81e69cd4b3d/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyaXRuZXkiLCJpYXQiOjE3MTU2NzkwODF9.g0VQQzaeaq-so4JH0c37oJNRkbXllMkJwi1rBDMduaY
Content-Type: application/json

{
    "content": "INSANE.. THATS CRAZY"
}

